name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 18 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#4F46E5&color_dots=#f1f1f4,#c7d2fe,#a5b4fc,#6366f1,#4338ca
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#FAFAFA&color_dots=#17171d,#1e1b4b,#3730a3,#6366f1,#a5b4fc

      - name: Push snake to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
